server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
    register-default-servlet: true

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 40
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

# Rest Template
rest:
  template:
    connection-manager:
      default-max-per-route: 100
      max-total: 100
    client-http-request:
      evict-idle-connections: 10
      connect-timeout: 30000
      read-timeout: 30000

search:
  blog:
    kakao:
      end-point: "https://dapi.kakao.com"
      api-key: "22875c991cab332f34000dff19b0af90"
    naver:
      end-point: "https://openapi.naver.com"
      client-id: "rdqIEQ2ryQPDQWcgA7Qa"
      client-secret: "fXWPAamwdS"